// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_SIN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_SIN_H

double sin(double x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_SIN_H
