// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_EXIT_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_EXIT_H

void exit(int code);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_EXIT_H
